import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { ProjectNode } from './types.js';

export async function generate(project: ProjectNode, outputDir: string): Promise<string[]> {
  const generated: string[] = [];
  await mkdir(outputDir, { recursive: true });

  const readme = `# ${project.name}\n\nGenerated by LeadOS Factory v0.1.\n\n## Stack\n\n${Object.entries(project.stack).map(([key, value]) => `- **${key}:** ${value}`).join('\n')}\n\n## Modules\n\n${project.modules.map((m) => `- ${m.id}`).join('\n')}\n`;
  const readmePath = join(outputDir, 'README.md');
  await writeFile(readmePath, readme, 'utf8');
  generated.push(readmePath);

  const manifestPath = join(outputDir, 'factory-manifest.json');
  await writeFile(manifestPath, JSON.stringify({ apiVersion: 'factory.leados.dev/v1', project }, null, 2) + '\n', 'utf8');
  generated.push(manifestPath);

  for (const module of project.modules) {
    const moduleDir = join(outputDir, 'modules', module.id);
    await mkdir(moduleDir, { recursive: true });
    const modulePath = join(moduleDir, 'README.md');
    await writeFile(modulePath, `# ${module.id}\n\nGenerated module.\n`, 'utf8');
    generated.push(modulePath);
  }

  return generated;
}
