package com.example.engine

import com.example.model.ArtifactType
import com.example.model.GeneratedArtifact
import com.example.model.ProjectNode

object BlueprintGenerator {

    /**
     * Compiles a ProjectNode AST into a complete set of generated file artifacts.
     */
    fun generate(project: ProjectNode, outputDir: String = ".factory-output"): List<GeneratedArtifact> {
        val artifacts = mutableListOf<GeneratedArtifact>()

        // 1. Root README.md
        val stackList = project.stack.toMap().entries.joinToString("\n") { (key, value) ->
            "- **$key:** $value"
        }
        val modulesList = project.modules.joinToString("\n") { "- ${it.id}" }
        val readmeContent = """
# ${project.name}

Generated by LeadOS Factory v0.1.

## Stack

$stackList

## Modules

$modulesList
        """.trimIndent() + "\n"

        artifacts.add(
            GeneratedArtifact(
                path = "$outputDir/README.md",
                filename = "README.md",
                content = readmeContent,
                type = ArtifactType.MARKDOWN
            )
        )

        // 2. factory-manifest.json
        val manifestContent = buildManifestJson(project)
        artifacts.add(
            GeneratedArtifact(
                path = "$outputDir/factory-manifest.json",
                filename = "factory-manifest.json",
                content = manifestContent,
                type = ArtifactType.JSON
            )
        )

        // 3. Module directories & READMEs
        for (module in project.modules) {
            val moduleReadme = "# ${module.id}\n\nGenerated module.\n"
            artifacts.add(
                GeneratedArtifact(
                    path = "$outputDir/modules/${module.id}/README.md",
                    filename = "README.md",
                    content = moduleReadme,
                    type = ArtifactType.MARKDOWN,
                    module = module.id
                )
            )

            // Module scaffold file
            val moduleScaffold = generateModuleScaffold(module.id, project)
            artifacts.add(
                GeneratedArtifact(
                    path = "$outputDir/modules/${module.id}/index.ts",
                    filename = "index.ts",
                    content = moduleScaffold,
                    type = ArtifactType.SOURCE,
                    module = module.id
                )
            )
        }

        // 4. Environment & deployment configuration
        val envContent = """
# LeadOS Factory Environment Config
PROJECT_NAME=${project.name}
PROJECT_TYPE=${project.type}
FRONTEND_TARGET=${project.stack.frontend}
BACKEND_TARGET=${project.stack.backend}
DATABASE_URL=postgresql://localhost:5432/${project.name.lowercase()}
AI_PROVIDER=${project.stack.ai}
DEPLOY_TARGET=${project.stack.deploy}
ENABLE_GITHUB_SYNC=${project.outputs.github}
ENABLE_NOTION_SYNC=${project.outputs.notion}
        """.trimIndent()

        artifacts.add(
            GeneratedArtifact(
                path = "$outputDir/.env.example",
                filename = ".env.example",
                content = envContent,
                type = ArtifactType.CONFIG
            )
        )

        return artifacts
    }

    private fun buildManifestJson(project: ProjectNode): String {
        val stackJson = project.stack.toMap().entries.joinToString(",\n      ") { (k, v) ->
            "\"$k\": \"$v\""
        }
        val modulesJson = project.modules.joinToString(",\n      ") { m ->
            val deps = m.dependsOn.joinToString(", ") { "\"$it\"" }
            """{"kind": "${m.kind}", "id": "${m.id}", "dependsOn": [$deps]}"""
        }

        return """
{
  "apiVersion": "factory.leados.dev/v1",
  "project": {
    "kind": "${project.kind}",
    "name": "${project.name}",
    "type": "${project.type}",
    "stack": {
      $stackJson
    },
    "modules": [
      $modulesJson
    ],
    "outputs": {
      "github": ${project.outputs.github},
      "notion": ${project.outputs.notion}
    }
  }
}
        """.trimIndent() + "\n"
    }

    private fun generateModuleScaffold(moduleId: String, project: ProjectNode): String {
        return """
/**
 * LeadOS Factory Scaffold: ${project.name} - Module: $moduleId
 * Generated automatically by LeadOS declarative factory.
 */

export interface ${moduleId.replace(Regex("[^a-zA-Z0-9]"), "").replaceFirstChar { it.uppercase() }}Config {
  moduleId: '$moduleId';
  enabled: boolean;
  version: string;
}

export class ${moduleId.replace(Regex("[^a-zA-Z0-9]"), "").replaceFirstChar { it.uppercase() }}Module {
  private readonly id = '$moduleId';

  constructor(private readonly config: ${moduleId.replace(Regex("[^a-zA-Z0-9]"), "").replaceFirstChar { it.uppercase() }}Config) {}

  public async initialize(): Promise<void> {
    console.log(`[LeadOS] Initializing module: ${'$'}{this.id} for project ${project.name}`);
  }

  public async executePipeline(): Promise<{ success: boolean; moduleId: string }> {
    return { success: true, moduleId: this.id };
  }
}
        """.trimIndent()
    }
}
